services:
  mc:
    image: itzg/minecraft-server:java17
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      MEMORY: "8G"
      VERSION: "1.18.2"
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_FILE_ID: "5951422"
      CF_SLUG: "my_modpack_1338"
      CF_API_KEY: '$$2a$$10$$8zrBIEXkIX5R2w0JjAR9a.lj3rrj.iXyyGEreOXuRSOFFOGyU.cHK'
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data